### ISSUE TITLE
fleakr <= 0.6.2 and ActiveSupport 2.3.5 incompatible

### ISSUE THREAD

**Issue by base10** [reagent/fleakr#6]
With fleakr 0.5.1 and 0.6.2, I run into the following error trying to require fleakr in a script:

/Library/Ruby/Gems/1.8/gems/activesupport-2.3.5/lib/active_support/core_ext/blank.rb:2: uninitialized constant ActiveSupport::Deprecation (NameError)

It appears that in ActiveSupport 2.3.5, active_support/core_ext/blank was deprecated for active_support/core_ext/object/blank. active_support/core_ext/blank requires active_support/core_ext/object/blank, but without including active_support/deprecation and its dependencies, no dice.

I created a diff ( http://gist.github.com/250636 ), but this would raise your dependencies from ActiveSupport 2.0 to 2.3.5 specifically.

Thank you,

Nathan
nwalls <at> ismedia -dot- org

**Comment by reagent** [comment]
I think the real solution here is to get rid of the dependency on ActiveSupport entirely.  There are only a couple places that I'm using it, and even then, it was just used as a quick addition to get the features I wanted.  

In the meantime, it might be possible to wrap the requre in a begin ... rescue block to handle both 2.0.x and 2.3.5

**Comment by base10** [comment]
That's certainly a lot more flexible than my "found after midnight" suggestion. Cheers.

**Comment by reagent** [comment]
I have yet to do this, but I would need you to test it for me anyway.  Would you be able to fork, commit, and test?  Then I can pull your change and push out 0.6.3

let me know.

**Comment by base10** [comment]
Sorry for the long delay, but I've pushed e77b4e0ffce85d374f97e71cdbe3d451ded93e6e in my fork to add a begin/rescue block. However, I'm currently unable to get the tests to run since it seems Test::Unit isn't thrilled with NameError. I spotted that last night and haven't had time to dig into it much.

**Comment by reagent** [comment]
Thanks for doing this - I'll pull it in tonight / tomorrow and get out a new version.  I'm not too concerned with tests for this since I'm planning to rip out AS entirely.

**Comment by base10** [comment]
Glad to do it. I greatly appreciate having fleakr available. Cheers.

**Comment by reagent** [comment]
Applied (finally) and released as 0.6.3 - thanks!

**Comment by slant** [comment]
I'm still getting this error on 0.6.3. Are there still plans to remove ActiveSupport? Perhaps this is yet another change to that same area of AS.

Thanks!

**Comment by reagent** [comment]
Thanks for the nudge, I need to get back on this.  Assuming that this isn't too complex, I'll get this in the next release (there's some code in master that isn't in the official gem that should be there as well)

**Comment by reagent** [comment]
This commit removes the dependency on AS:

https://github.com/reagent/fleakr/commit/c498243cc9f54db33bfc1acf62deb7c4fa58b9fb

I will be tidying up the documentation and will release 0.7.0 in the next day or so.
